version: '3.8'
services:
  #
  # We begin with the reverse proxy stack
  # reference : 
  swag-proxy:
    image: lscr.io/linuxserver/swag
    container_name: ${COMPOSE_PROJECT_NAME}_swag-entrypoint
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${PWD}/data/swag/config:/config
      # Uncomment the following line to push to name based volumes for production
      # swag-config:/config
      - certs:/etc/letsencrypt/
    env_file:
      - .env_swag-variables
    environment:
      - URL=${VIRTUAL_HOST}
      - EMAIL=${CERTBOT_EMAIL}
      # Uncomment if you're deploying on a main domain to activate subdomains like :
      #- SUBDOMAINS=www,ftp,cloud 
    cap_add:
      - NET_ADMIN
    networks:
      - revproxy_admin
      - revproxy_apps
  #
  # Now comes the Authelia container
  authelia:
    container_name: ${COMPOSE_PROJECT_NAME}_authelia
    image: authelia/authelia
    restart: unless-stopped
    command: 
      - "authelia" 
      - "--config /config/configuration.yaml"
      - "--config /config/configuration.acl.yaml"

    expose:
      - 9091
    volumes:
      - ${PWD}/data/authelia/config:/config
      # Uncomment the following line to push to name based volumes for production
      # authelia-config:/config
    environment:
      TZ: 'Australia/Melbourne'
    networks:
      - revproxy_admin
  # Redis image for Authelia
  # https://www.authelia.com/configuration/session/redis/
  authelia_redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_authelia_redis
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - redis:/data
    environment:
      - TZ=America/Chicago
    networks:
      - revproxy_admin

  # 
  # Now comes the admin services stack
  portainer:
    image: portainer/portainer-ce:latest
    container_name: ${COMPOSE_PROJECT_NAME}_portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    depends_on:
      - swag-proxy
    expose:
      - "9000"
    volumes:
      - ${PWD}/data/portainer:/data
      # Uncomment the following line to push to name based volumes for production
      # portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - revproxy_admin
  #
  # Server monitoring
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: ${COMPOSE_PROJECT_NAME}_homepage
    restart: always
    depends_on:
      - swag-proxy
    expose:
      - "3000"
    volumes:
      - ${PWD}/data/homepage:/app/config
      # Uncomment the following line to push to name based volumes for production
      # homepage-config:/app/config
      - html:/app/public
    networks:
      - revproxy_admin

volumes:
#  swag-config:
#  authelia-config:
#  portainer-data:
#  homepage-config:
  certs:
  html:
  redis:

networks:
  revproxy_admin:
    name: revproxy_admin
    external: true
  revproxy_apps:
    name: revproxy_apps
    external: true