version: '3'


services:
  #
  # We begin with the reverse proxy stack
  # reference : https://github.com/nginx-proxy/acme-companion/blob/main/docs/Docker-Compose.md
  nginx-proxy:
    build: ./proxy
    container_name: ${COMPOSE_PROJECT_NAME}_entrypoint
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - proxy-tier
      - revproxy_admin
      - revproxy_apps

  acme-companion:
    image: nginxproxy/acme-companion:latest
    container_name: ${COMPOSE_PROJECT_NAME}_entrypoint_acme
    restart: always
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier

  # 
  # Now comes the admin services stack
  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    container_name: ${COMPOSE_PROJECT_NAME}_portainer
    restart: always
    depends_on:
      - nginx-proxy
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - revproxy_admin

volumes:
  acme:
  certs:
  conf:
  html:
  portainer-data:
  vhost:

networks:
  proxy-tier:
  revproxy_admin:
    name: revproxy_admin
    external: true
  revproxy_apps:
    name: revproxy_apps
    external: true