version: '3'


services:
  #
  # We begin with the reverse proxy stack
  nginx-proxy:
    build: ./proxy
    container_name: ${COMPOSE_PROJECT_NAME}_entrypoint
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - proxy-tier
      - revproxy_admin
      - revproxy_apps

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    container_name: ${COMPOSE_PROJECT_NAME}_entrypoint_le_companion
    restart: always
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    networks:
      - proxy-tier

  # 
  # Now comes the admin services stack
  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    container_name: ${COMPOSE_PROJECT_NAME}_portainer
    restart: always
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - revproxy_admin

  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: ${COMPOSE_PROJECT_NAME}_homepage
    restart: always
    expose:
      - "3000"
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}=value
    volumes:
      - ./homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - revproxy_admin

  # 
  # Finally the security layer
  authelia:
    image: authelia/authelia
    container_name: ${COMPOSE_PROJECT_NAME}_authelia
    restart: always
    volumes:
      - ./authelia:/config
    networks:
      - revproxy_admin


volumes:
  certs:
  vhost.d:
  html:
  portainer-data:

networks:
  proxy-tier:
  revproxy_admin:
    external:
      name: ${ADMIN_NETWORK}
  revproxy_apps:
    external: 
      name: ${APPS_NETWORK}