version: '3'

services:
  nginx-proxy:
    build: ./proxy
    container_name: nginx_proxy4${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - proxy-tier
      - backend
      - apps

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    container_name: proxy-certs4frontend
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer4frontend
    restart: always
    expose:
      - "9000"
    environment:
    # Modify the following lines to fit your needs
    # -> replace "your-domain.ltd" with a DNS valid domain name associated with your server
    # -> replace "letsencrypt-email@mail-provider.ltd" with the mail address registered in the Let's encrypt service
      - VIRTUAL_HOST=portainer.your-domain.ltd
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.your-domain.ltd
      - LETSENCRYPT_EMAIL=letsencrypt-email@mail-provider.ltd
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data

volumes:
  certs:
  vhost.d:
  html:

networks:
  backend:
  proxy-tier:
  apps: