version: '3'

services:
  nginx-proxy:
    build: ./proxy
    container_name: ${COMPOSE_PROJECT_NAME}_entrypoint
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - proxy-tier
      - revproxy_admin
      - revproxy_apps

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    container_name: ${COMPOSE_PROJECT_NAME}_entrypoint_le_companion
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier

  portainer:
    image: portainer/portainer-ce:latest
    container_name: ${COMPOSE_PROJECT_NAME}_portainer
    restart: always
    expose:
      - "9000"
    environment:
      - VIRTUAL_HOST=${PORTAINER_VHOST}
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=${PORTAINER_VHOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - revproxy_admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data
    networks:
      - revproxy_admin

volumes:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
  revproxy_admin:
    external:
      name: ${ADMIN_NETWORK}
  revproxy_apps:
    external: 
      name: ${APPS_NETWORK}