version: '3.8'
services:
  #
  # We begin with the reverse proxy stack
  # reference :
  swag-proxy:
    image: lscr.io/linuxserver/swag
    container_name: ${COMPOSE_PROJECT_NAME}_swag-entrypoint
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${PWD}/config/swag/config:/config
      ## Uncomment the line below if you want to use the Authelia configuration snippets.
      #- '${PWD}/config/swag/snippets:/snippets'
    environment:
      - PUID=1000
      - PGID=1000
      - URL=${VIRTUAL_HOST}
      - EMAIL=${CERTBOT_EMAIL}
      - SUBDOMAINS=${SUBDOMAINS}
      - ONLY_SUBDOMAINS=false
      - DOCKER_MODS=linuxserver/mods:swag-dashboard
    cap_add:
      - NET_ADMIN
    networks:
      - revproxy_admin
      - revproxy_apps

  #
  # Admin services stack
  portainer:
    image: portainer/portainer-ce:latest
    container_name: ${COMPOSE_PROJECT_NAME}_portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    depends_on:
      - swag-proxy
    expose:
      - "9000"
    volumes:
      - ${PWD}/config/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - revproxy_admin

  #
  # Server monitoring
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: ${COMPOSE_PROJECT_NAME}_homepage
    restart: always
    depends_on:
      - swag-proxy
    expose:
      - "3000"
    volumes:
      - ${PWD}/config/homepage:/app/config
      - html:/app/public
    networks:
      - revproxy_admin

  #
  # File browser
  # See https://github.com/hurlenko/filebrowser-docker for more information
  filebrowser:
    image: hurlenko/filebrowser
    container_name: ${COMPOSE_PROJECT_NAME}_filebrowser
    restart: always
    depends_on:
      - swag-proxy
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
      - FB_BASEURL=/data
      # The list of avalable options can be found here : https://filebrowser.org/cli/filebrowser#options.
    expose:
      - "443:8080" 
    volumes:
      - ${PWD}/config/filebrowser/filebrowser.db:/database/filebrowser.db 
      - ${PWD}/config/filebrowser/config:/config/
      - ${PWD}/config/homepage:/app/config
      # 
      # From here place other services data folders
      - ${PWD}/config/swag/config/nginx:/data/config-swag
      - ${PWD}/config/portainer:/data/config-portainer
      - ${PWD}/config/homepage:/data/config-homepage
      - ${PWD}/config/authelia/config:/data/config-authelia
    networks:
      - revproxy_admin

  #
  # Now comes the Authelia container
  authelia:
    container_name: ${COMPOSE_PROJECT_NAME}_authelia
    image: authelia/authelia
    restart: unless-stopped
    depends_on:
      - swag-proxy
      - authelia_redis
    expose:
      - 9091
    volumes:
      - ${PWD}/config/authelia/config:/config
    networks:
      - revproxy_admin

  # Redis image for Authelia
  # https://www.authelia.com/configuration/session/redis/
  authelia_redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_authelia_redis
    restart: unless-stopped
    depends_on:
      - swag-proxy
    expose:
      - 6379
    volumes:
      - redis:/data
    networks:
      - revproxy_admin

volumes:
#  swag-config:
#  authelia-config:
#  portainer-data:
#  homepage-config:
  html:
  redis:

networks:
  revproxy_admin:
    name: revproxy_admin
    external: true
  revproxy_apps:
    name: revproxy_apps
    external: true
