#
# Homepage configuration (https://gethomepage.dev/en/configs/services/)
# For icons, just specify the service name from https://github.com/walkxcode/dashboard-icons/tree/main/

#
# Then the services section
- Administration:
    - Portainer:
        icon: portainer-alt.png
        href: https://changeme/portainer/
        description: Portainer docker stack management interface
        # (Optional) ping : works by sending a HTTP HEAD request to the server
        ping: https://changeme/portainer/
        
    - File browser:
        icon: filebrowser.png
        href: http://changeme/data
        description: Manages reverse proxy files and assets with ease!
        # (Optional) ping : works by sending a HTTP HEAD request to the server
        ping: http://changeme

    - SWAG Dashboard:
        icon: goaccess.png
        href: https://dash.changeme/
        description: SWAG reverse proxy monitoring dashboard
        # (Optional) ping : works by sending a HTTP HEAD request to the server
        ping: https://dash.changeme/

    - Authelia:
        icon: authelia.png
        href: https://authchangeme/
        description: RBAS authentication portal
        # (Optional) ping : works by sending a HTTP HEAD request to the server
        ping: https://authchangeme
