###############################################################
#                   Authelia configuration                    #
###############################################################

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
# Please tweak and modify some symbol to fit your needs.
jwt_secret: A4gYb7QFpbfKaNWAX7P7FX5y
default_redirection_url: https://redirecturl

server:
  host: 0.0.0.0
  port: 9091 # if you need this changed make sure it reflects also in the docker-compose.yml

log:
  level: info
  format: text

#access_control:
#  default_policy: 'deny'
#  rules:
#    # Rules applied to everyone
#    - domain: 'public.elasticlabs.com'
#      policy: 'bypass'
#    - domain: 'labs.example.com'
#      policy: 'two_factor'

authentication_backend:
  file:
    path: '/config/users.yml'
    watch: false
    search:
      email: false
      case_insensitive: false
    password:
      algorithm: 'argon2'
      argon2:
        variant: 'argon2id'
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

totp:
  issuer: authelia.com

# Activate this once you created the free Duo API protected application in Duo dashboard
#duo_api:
#  disable: false
#  hostname: <api-domain>.duosecurity.com
#  integration_key: <integration_key>
#  secret_key: <secret_key>
#  enable_self_enrollment: true

session:
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: unsecure_session_secret
  cookies:
    - name: authelia_session
      domain: changeme  # Should match whatever your root protected domain is
      expiration: 3600  # 1 hour
      inactivity: 300  # 5 minutes

  redis:
    host: authelia_redis
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt

#  smtp:
#    username: test
#    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
#    password: password
#    host: mail.example.com
#    port: 25
#    sender: admin@example.com
#...
