###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

users:
  authelia:
    disabled: false
    displayname: "Authelia Test User"
    password: "$argon2id$v=19$m=32768,t=1,p=8$eUhVT1dQa082YVk2VUhDMQ$E8QI4jHbUBt3EdsU1NFDu4Bq5jObKNx7nBKSn1EYQxk"  # Password is 'authelia'
    email: authelia@authelia.com
    groups:
      - admins
      - dev
  proxyadmin:
    disabled: false
    displayname: "Proxy Admin"
    password: "$argon2id$v=19$m=65536,t=3,p=4$qloVvwb6Hc38Gy+ZuPgn+g$low/awIk/j12ddjIaLcnsSjqISwfaE8K5yNLkdXQjfo"  # Password is 'password'
    email: admin@example.com
    groups:
      - admins
...
# yamllint enable rule:line-length
