# Global configuration
host: 0.0.0.0
port: 9091
tls:
  enabled: false

# OAuth2 configuration for GitHub
authentication_backend:
  # Use GitHub as the OAuth2 provider
  name: github
  # Replace these values with your own GitHub API credentials
  client_id: "your-github-client-id"
  client_secret: "your-github-client-secret"
  # Specify the GitHub organizations and teams to allow access for
  organizations:
    - name: "your-github-organization"
      teams:
        - "your-github-team"
  # Specify the user groups to allow access for
  groups:
    - "your-github-group"

# Access configuration
access_control:
  default_policy: deny
  rules:
    # Allow access to the nginx-proxy and portainer services for users in the specified GitHub teams and groups
    - domain: labs.elasticlabs.co
      policy: allow
      resources:
        - path: "/nginx-proxy"
        - path: "/portainer"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
      subject:
        github:
          organizations:
            - name: "your-github-organization"
              teams:
                - "your-github-team"
          groups:
            - "your-github-group"
    # Allow access to the netdata service for users in the specified GitHub teams and groups
    - domain: labs.elasticlabs.co
      policy: allow
      resources:
        - path: "/netdata"
      methods:
        - GET
      subject:
        github:
          organizations:
            - name: "your-github-organization"
              teams:
                - "your-github-team"
          groups:
            - "your-github-group"
    # Deny access to everything else
    - domain: labs.elasticlabs.co
      policy: deny